apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/backend-config: '{"default": "keycloak"}'
  labels:
    app: keycloak
    app.version: "1"
  name: keycloak
  namespace: cdip-auth
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 32431
    port: 8080
  selector:
    app: keycloak
  type: LoadBalancer
