# Generated by Django 3.1 on 2020-10-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_device_state_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundintegrationtype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Type'),
        ),
    ]
