# Generated by Django 3.1 on 2020-11-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_auto_20201012_1633'),
        ('integrations', '0013_inboundintegrationconfiguration_encrypted_password_field'),
    ]

    operations = [
    ]
