# Generated by Django 3.1 on 2020-11-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_inboundintegrationconfiguration_encrypted_password_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundintegrationconfiguration',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
