# Generated by Django 3.1 on 2021-01-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_oc_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundintegrationconfiguration',
            name='state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inboundintegrationtype',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='outboundintegrationconfiguration',
            name='state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outboundintegrationtype',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
