# Generated by Django 3.1 on 2021-03-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0026_device_index_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicegroup',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='devicestate',
            options={'ordering': ('device', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='inboundintegrationtype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='outboundintegrationconfiguration',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='outboundintegrationtype',
            options={'ordering': ('name',)},
        ),
    ]
