apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: "${KUBERNETES_NAMESPACE}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airflow
  template:
    metadata:
      labels:
        name: airflow
    spec:
      serviceAccountName: airflow-serviceaccount
      initContainers:
        - name: init-airflow
          image: "${AIRFLOW_IMAGE_NAME}:${AIRFLOW_IMAGE_TAG}"
          imagePullPolicy: Always
          # TODO: create script to do any pre-config for nfs, initial user account, AF connection config
          command: ['sh', '-c', "airflow initdb"]
          volumeMounts:
            - name: airflow-configmap
              mountPath: /root/airflow/airflow.cfg
              subPath: airflow.cfg
              readOnly: true
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: cdip-secrets
                  key: airflow.sql_alchemy_conn
      containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.2.0
          imagePullPolicy: IfNotPresent
          args:
            - "--repo=https://github.com/PADAS/cdip-downstream.git"
            - "--dest=cdip-downstream"
            - "--branch=master"
            - "--depth=1"
            - "--wait=30"
            - "--root=/tmp/git/srcroot"
          env:
            - name: GIT_SYNC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cdip-secrets
                  key: GIT_SYNC_USERNAME
            - name: GIT_SYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cdip-secrets
                  key: GIT_SYNC_PASSWORD
          securityContext:
            runAsUser: 0 # root
          volumeMounts:
            - name: airflow-dags
              mountPath: /tmp/git
              readOnly: false
        - name: webserver
          image: "${AIRFLOW_IMAGE_NAME}:${AIRFLOW_IMAGE_TAG}"
          imagePullPolicy: IfNotPresent
          args: ["webserver"]
          ports:
            - name: webserver
              containerPort: 8080
          livenessProbe:
            exec:
              command:
                - python3
                - /workspace/healthcheck.py
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: airflow-configmap
              mountPath: /root/airflow/airflow.cfg
              subPath: airflow.cfg
            - name: airflow-dags
              mountPath: /git-sync
              readOnly: true
          envFrom:
            - configMapRef:
                name: dags-configmap
            - configMapRef:
                name: keycloak-configmap
            - secretRef:
                name: cdip-secrets
        - name: scheduler
          image: "${AIRFLOW_IMAGE_NAME}:${AIRFLOW_IMAGE_TAG}"
          imagePullPolicy: IfNotPresent
          args: ["scheduler"]
          livenessProbe:
            exec:
              command:
                - python3
                - /workspace/healthcheck.py
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: airflow-configmap
              mountPath: /root/airflow/airflow.cfg
              subPath: airflow.cfg
            - name: airflow-dags
              mountPath: /git-sync
              readOnly: true
          envFrom:
            - configMapRef:
                name: dags-configmap
            - configMapRef:
                name: keycloak-configmap
            - secretRef:
                name: cdip-secrets
        - name: telegraf
          image: telegraf:1.15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8125
          volumeMounts:
            - name: telegraf-config-volume
              mountPath: "/etc/telegraf/"
              readOnly: true
            - name: metrics-writer-credentials
              mountPath: "/etc/cdip/"
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/cdip/metrics-writer-credentials.json"
      volumes:
        - name: airflow-configmap
          configMap:
            name: airflow-configmap
        - name: airflow-dags
          persistentVolumeClaim:
            claimName: ${AIRFLOW_DAGS_VOLUME_CLAIM}
        - name: telegraf-config-volume
          configMap:
            name: telegraf-configmap
            items:
            - key: telegraf_conf
              path: telegraf.conf
        - name: metrics-writer-credentials
          secret:
            secretName: metrics-writer-credentials
            items:
            - key: credentials_json
              path: metrics-writer-credentials.json


---
apiVersion: v1
kind: Service
metadata:
  namespace: "${KUBERNETES_NAMESPACE}"
  name: airflow
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: airflow
