apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${AIRFLOW_LOGS_VOLUME}"
  namespace: "${KUBERNETES_NAMESPACE}"
spec:
  accessModes:
    - ReadWriteOnce  # TODO: need r/w many here? will need non-default storage class
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${AIRFLOW_DAGS_VOLUME}"
  namespace: "${KUBERNETES_NAMESPACE}"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Mi
