apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs
  namespace: test-airflow
spec:
  accessModes:
    - ReadWriteOnce  # TODO: need r/w many here? will need non-default storage class
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags
  namespace: test-airflow
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
