---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${AIRFLOW_DAGS_VOLUME_CLAIM}"
  namespace: "${KUBERNETES_NAMESPACE}"
spec:
  storageClassName: "" # this prevents the default assignment to gce standard storage class.
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---
# persistent volumes are not bound to a k8s namespace
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${AIRFLOW_DAGS_VOLUME}
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.cdip-v1.svc.cluster.local
    path: "/exports/dags"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: "${KUBERNETES_NAMESPACE}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: "${KUBERNETES_NAMESPACE}"
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      initContainers:
        - name: init-exported-volume
          image: gcr.io/google_containers/volume-nfs:0.8
          command: ['mkdir', '-p', '/exports/dags']
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /exports
              name: exported-volume
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: exported-volume
      volumes:
        - name: exported-volume
          persistentVolumeClaim:
            claimName: nfs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: "${KUBERNETES_NAMESPACE}"
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server