apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-serviceaccount
  namespace: ${KUBERNETES_NAMESPACE}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-role
  namespace: ${KUBERNETES_NAMESPACE}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-rolebinding
  namespace: ${KUBERNETES_NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: airflow-serviceaccount
roleRef:
  kind: Role # This must be Role or ClusterRole
  name: airflow-role
  apiGroup: rbac.authorization.k8s.io