# Generated by Django 3.1 on 2021-01-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientaudiencescope_inboundclientscope_outboundclientscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='client_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
