# Generated by Django 3.1 on 2021-05-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_role_dropdown_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountprofile',
            old_name='user_id',
            new_name='user_username',
        ),
    ]
