# Generated by Django 3.1 on 2021-05-05 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_rename_user_id_to_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "update accounts_accountprofile set user_id = au.id from auth_user au where user_username = au.username"
        )
    ]
