# Generated by Django 3.0.7 on 2020-06-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundintegrationtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='outboundintegrationtype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
