# Generated by Django 3.0.7 on 2020-07-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_auto_20200630_1632"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboundintegrationconfiguration",
            name="slug",
        ),
        migrations.AddField(
            model_name="device",
            name="cursor",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="inboundintegrationconfiguration",
            name="cursor",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="inboundintegrationconfiguration",
            name="defaultConfiguration",
            field=models.ManyToManyField(
                to="integrations.OutboundIntegrationConfiguration"
            ),
        ),
        migrations.AddField(
            model_name="inboundintegrationconfiguration",
            name="login",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="inboundintegrationconfiguration",
            name="password",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="inboundintegrationconfiguration",
            name="token",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="inboundintegrationconfiguration",
            name="useAdvancedConfiguration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inboundintegrationconfiguration",
            name="useDefaultConfiguration",
            field=models.BooleanField(default=True),
        ),
    ]
