# Generated by Django 3.1 on 2020-08-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0006_auto_20200824_1915"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="cursor",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="inboundintegrationconfiguration",
            name="cursor",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="outboundintegrationconfiguration",
            name="cursor",
            field=models.JSONField(default=dict),
        ),
    ]
