# Generated by Django 3.1 on 2020-08-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_auto_20200824_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='cursor',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='inboundintegrationconfiguration',
            old_name='cursor',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='outboundintegrationconfiguration',
            old_name='cursor',
            new_name='state',
        ),
    ]
