# Generated by Django 3.1 on 2020-09-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0010_auto_20200915_1843"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="name",
            new_name="external_id",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="type",
            new_name="inbound_configuration",
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("inbound_configuration", "external_id")},
        ),
        migrations.RemoveField(
            model_name="device",
            name="location",
        ),
        migrations.RemoveField(
            model_name="device",
            name="owner",
        ),
    ]
