# Generated by Django 3.1.1 on 2020-09-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_auto_20200915_1937'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicestate',
            index=models.Index(fields=['device', 'created_at'], name='integration_device__a5e595_idx'),
        ),
    ]
