# Generated by Django 3.1 on 2021-02-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0017_auto_20210210_1257"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("external_id", "inbound_configuration")},
        ),
    ]
