# Generated by Django 3.1 on 2021-02-23 00:58

from django.db import migrations


def forward_f(apps, schema_editor):

    DeviceGroup = apps.get_model("integrations", "DeviceGroup")
    Device = apps.get_model("integrations", "Device")
    InboundIntegrationConfiguration = apps.get_model(
        "integrations", "InboundIntegrationConfiguration"
    )

    db_alias = schema_editor.connection.alias

    for iic in InboundIntegrationConfiguration.objects.all():

        # calculate a sensible name
        name = iic.name or f"{iic.type.name}-{iic.owner.name}"
        dg = DeviceGroup.objects.create(
            name=f"Default Group for {name}",
            owner=iic.owner,
            inbound_configuration=iic,
        )

        # Associate exisitng default outbound config with this new Device Group.
        dg.devices.add(*[x for x in Device.objects.filter(inbound_configuration=iic)])
        for oc in iic.defaultConfiguration.all():
            dg.destinations.add(oc)


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0022_devicegroups"),
    ]

    operations = [
        migrations.RunPython(forward_f, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="inboundintegrationconfiguration",
            name="defaultConfiguration",
        ),
    ]
