# Generated by Django 3.1 on 2021-02-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0024_prune_devicegroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicegroup",
            name="inbound_configuration",
        ),
    ]
