# Generated by Django 3.2 on 2021-06-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0030_bridgeintegration_consumer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundintegrationconfiguration",
            name="consumer_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
