# Generated by Django 3.1.5 on 2021-10-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0033_default_provider_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='additional',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
