# Generated by Django 3.1.5 on 2021-12-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0035_default_dict_externalId"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
