# Generated by Django 3.1.5 on 2021-12-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0038_devicegroup_default_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='subject_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.subjecttype'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='default_subject_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.subjecttype'),
        ),
    ]
