# Generated by Django 3.2 on 2022-08-04 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0008_auto_20220804_1846"),
        ("integrations", "0039_subject_type_deletion_protect"),
    ]

    operations = [
        migrations.CreateModel(
            name="GFWInboundConfiguration",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("integrations.inboundintegrationconfiguration",),
        ),
        migrations.AlterField(
            model_name="inboundintegrationconfiguration",
            name="provider",
            field=models.CharField(
                blank=True,
                help_text="This value will be used as the 'provider_key' when sending data to EarthRanger.",
                max_length=200,
                verbose_name="Provider_key",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalInboundIntegrationConfiguration",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("endpoint", models.URLField(blank=True)),
                ("state", models.JSONField(blank=True, null=True)),
                ("login", models.CharField(blank=True, max_length=200)),
                (
                    "password",
                    fernet_fields.fields.EncryptedCharField(blank=True, max_length=200),
                ),
                (
                    "token",
                    fernet_fields.fields.EncryptedCharField(blank=True, max_length=200),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="This value will be used as the 'provider_key' when sending data to EarthRanger.",
                        max_length=200,
                        verbose_name="Provider_key",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("consumer_id", models.CharField(blank=True, max_length=200)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "default_devicegroup",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="inbound_integration_configurations",
                        to="integrations.devicegroup",
                        verbose_name="Default Device Group",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrations.inboundintegrationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical inbound integration configuration",
                "verbose_name_plural": "historical inbound integration configurations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
