# Generated by Django 3.2 on 2022-08-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "integrations",
            "0043_historicalbridgeintegration_historicalbridgeintegrationtype_historicaldevice_historicaldevicegroup_h",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalinboundintegrationconfiguration",
            name="state",
        ),
        migrations.DeleteModel(
            name="HistoricalDeviceState",
        ),
    ]
