# Generated by Django 3.2 on 2022-09-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20220804_1846'),
        ('integrations', '0044_auto_20220817_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='additional',
            field=models.JSONField(blank=True, default=dict, help_text='Additional config(s)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='external_id',
            field=models.CharField(help_text='Id sent by the data provider', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='subject_type',
            field=models.ForeignKey(blank=True, help_text='Default subject type. Can be overriden by the integration or data provider', null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.subjecttype'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='default_subject_type',
            field=models.ForeignKey(blank=True, help_text='Subject type to be used unless overriden by the integration or data provider.', null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.subjecttype'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='destinations',
            field=models.ManyToManyField(blank=True, help_text='Outbound Integration.', related_name='devicegroups', related_query_name='devicegroup', to='integrations.OutboundIntegrationConfiguration'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='owner',
            field=models.ForeignKey(help_text='Organization that owns the data.', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='additional',
            field=models.JSONField(blank=True, default=dict, help_text='Additional config(s)'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='external_id',
            field=models.CharField(help_text='Id sent by the data provider', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='subject_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Default subject type. Can be overriden by the integration or data provider', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.subjecttype'),
        ),
        migrations.AlterField(
            model_name='historicaldevicegroup',
            name='default_subject_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subject type to be used unless overriden by the integration or data provider.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.subjecttype'),
        ),
        migrations.AlterField(
            model_name='historicaldevicegroup',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Organization that owns the data.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='historicalgfwinboundconfiguration',
            name='default_devicegroup',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Device group that will be used unless a different group is specified by the data provider or integration.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='inbound_integration_configurations', to='integrations.devicegroup', verbose_name='Default Device Group'),
        ),
        migrations.AlterField(
            model_name='historicalgfwinboundconfiguration',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='EarthRanger site or destination system that owns the data.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='historicalgfwinboundconfiguration',
            name='state',
            field=models.JSONField(blank=True, help_text='Additional integration configuration(s).', null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='historicalgfwinboundconfiguration',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Data Provider configured as an Inbound Type.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.inboundintegrationtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalinboundintegrationconfiguration',
            name='default_devicegroup',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Device group that will be used unless a different group is specified by the data provider or integration.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='inbound_integration_configurations', to='integrations.devicegroup', verbose_name='Default Device Group'),
        ),
        migrations.AlterField(
            model_name='historicalinboundintegrationconfiguration',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='EarthRanger site or destination system that owns the data.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='historicalinboundintegrationconfiguration',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Data Provider configured as an Inbound Type.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.inboundintegrationtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalinboundintegrationtype',
            name='description',
            field=models.TextField(blank=True, help_text='Optional field - description of the Technology or Service.'),
        ),
        migrations.AlterField(
            model_name='historicalinboundintegrationtype',
            name='slug',
            field=models.SlugField(help_text='Identifier using lowercase letters and no spaces.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaloutboundintegrationconfiguration',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Destination system configured as an Outbound Type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='historicaloutboundintegrationconfiguration',
            name='state',
            field=models.JSONField(blank=True, help_text='Additional configuration(s).', null=True),
        ),
        migrations.AlterField(
            model_name='historicaloutboundintegrationconfiguration',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Destination system', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.outboundintegrationtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicaloutboundintegrationtype',
            name='description',
            field=models.TextField(blank=True, help_text='Optional - general description of the destination system.'),
        ),
        migrations.AlterField(
            model_name='historicaloutboundintegrationtype',
            name='slug',
            field=models.SlugField(help_text='Identifier using lowercase letters and no spaces.', max_length=200),
        ),
        migrations.AlterField(
            model_name='inboundintegrationconfiguration',
            name='default_devicegroup',
            field=models.ForeignKey(blank=True, help_text='Device group that will be used unless a different group is specified by the data provider or integration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_integration_configuration', related_query_name='inbound_integration_configurations', to='integrations.devicegroup', verbose_name='Default Device Group'),
        ),
        migrations.AlterField(
            model_name='inboundintegrationconfiguration',
            name='owner',
            field=models.ForeignKey(help_text='EarthRanger site or destination system that owns the data.', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='inboundintegrationconfiguration',
            name='state',
            field=models.JSONField(blank=True, help_text='Additional integration configuration(s).', null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='inboundintegrationconfiguration',
            name='type',
            field=models.ForeignKey(help_text='Data Provider configured as an Inbound Type.', on_delete=django.db.models.deletion.CASCADE, to='integrations.inboundintegrationtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='inboundintegrationtype',
            name='description',
            field=models.TextField(blank=True, help_text='Optional field - description of the Technology or Service.'),
        ),
        migrations.AlterField(
            model_name='inboundintegrationtype',
            name='slug',
            field=models.SlugField(help_text='Identifier using lowercase letters and no spaces.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='outboundintegrationconfiguration',
            name='owner',
            field=models.ForeignKey(help_text='Destination system configured as an Outbound Type', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='outboundintegrationconfiguration',
            name='state',
            field=models.JSONField(blank=True, help_text='Additional configuration(s).', null=True),
        ),
        migrations.AlterField(
            model_name='outboundintegrationconfiguration',
            name='type',
            field=models.ForeignKey(help_text='Destination system', on_delete=django.db.models.deletion.CASCADE, to='integrations.outboundintegrationtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='outboundintegrationtype',
            name='description',
            field=models.TextField(blank=True, help_text='Optional - general description of the destination system.'),
        ),
        migrations.AlterField(
            model_name='outboundintegrationtype',
            name='slug',
            field=models.SlugField(help_text='Identifier using lowercase letters and no spaces.', max_length=200, unique=True),
        ),
    ]
