# Generated by Django 3.2 on 2022-10-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20220804_1846'),
        ('integrations', '0047_init_erinreach_config_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgeintegration',
            name='owner',
            field=models.ForeignKey(help_text='Organization that owns the data.', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='bridgeintegration',
            name='state',
            field=models.JSONField(blank=True, help_text='Additional integration configuration(s).', null=True),
        ),
        migrations.AlterField(
            model_name='bridgeintegration',
            name='type',
            field=models.ForeignKey(help_text='Integration component that can process the data.', on_delete=django.db.models.deletion.CASCADE, to='integrations.bridgeintegrationtype'),
        ),
        migrations.AlterField(
            model_name='bridgeintegrationtype',
            name='description',
            field=models.TextField(blank=True, help_text='Optional - general description of the destination system.'),
        ),
        migrations.AlterField(
            model_name='bridgeintegrationtype',
            name='slug',
            field=models.SlugField(help_text='Identifier using lowercase letters and no spaces.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalbridgeintegration',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Organization that owns the data.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='historicalbridgeintegration',
            name='state',
            field=models.JSONField(blank=True, help_text='Additional integration configuration(s).', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbridgeintegration',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Integration component that can process the data.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.bridgeintegrationtype'),
        ),
        migrations.AlterField(
            model_name='historicalbridgeintegrationtype',
            name='description',
            field=models.TextField(blank=True, help_text='Optional - general description of the destination system.'),
        ),
        migrations.AlterField(
            model_name='historicalbridgeintegrationtype',
            name='slug',
            field=models.SlugField(help_text='Identifier using lowercase letters and no spaces.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalgfwinboundconfiguration',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Organization that owns the data.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='historicalgfwinboundconfiguration',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Integration component that can process the data.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.inboundintegrationtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalinboundintegrationconfiguration',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Organization that owns the data.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='historicalinboundintegrationconfiguration',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Integration component that can process the data.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.inboundintegrationtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicaloutboundintegrationconfiguration',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Organization that owns the data.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='historicaloutboundintegrationconfiguration',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Integration component that can process the data.”', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.outboundintegrationtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='inboundintegrationconfiguration',
            name='owner',
            field=models.ForeignKey(help_text='Organization that owns the data.', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='inboundintegrationconfiguration',
            name='type',
            field=models.ForeignKey(help_text='Integration component that can process the data.', on_delete=django.db.models.deletion.CASCADE, to='integrations.inboundintegrationtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='outboundintegrationconfiguration',
            name='owner',
            field=models.ForeignKey(help_text='Organization that owns the data.', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='outboundintegrationconfiguration',
            name='type',
            field=models.ForeignKey(help_text='Integration component that can process the data.”', on_delete=django.db.models.deletion.CASCADE, to='integrations.outboundintegrationtype', verbose_name='Type'),
        ),
    ]
