# Generated by Django 3.2.15 on 2022-11-29 19:17

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0048_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgeintegration',
            name='additional',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='historicalbridgeintegration',
            name='additional',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='historicaloutboundintegrationconfiguration',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Integration component that can process the data.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.outboundintegrationtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='outboundintegrationconfiguration',
            name='type',
            field=models.ForeignKey(help_text='Integration component that can process the data.', on_delete=django.db.models.deletion.CASCADE, to='integrations.outboundintegrationtype', verbose_name='Type'),
        ),
    ]
