# Generated by Django 3.2 on 2022-11-29 18:09

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0049_auto_20221116_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalgfwinboundconfiguration',
            name='state',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='inboundintegrationconfiguration',
            name='state',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict),
        ),
    ]
