# Generated by Django 3.2 on 2022-11-30 21:09

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0050_auto_20221129_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutboundintegrationtype',
            name='configuration_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='JSON Schema for configuration value'),
        ),
        migrations.AddField(
            model_name='outboundintegrationtype',
            name='configuration_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='JSON Schema for configuration value'),
        ),
        migrations.AlterField(
            model_name='historicaloutboundintegrationconfiguration',
            name='state',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='outboundintegrationconfiguration',
            name='state',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict),
        ),
    ]
