# Generated by Django 3.2.15 on 2023-03-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0051_auto_20221130_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgfwinboundconfiguration',
            name='default_devicegroup',
        ),
        migrations.RemoveField(
            model_name='historicalgfwinboundconfiguration',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalgfwinboundconfiguration',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalgfwinboundconfiguration',
            name='type',
        ),
        migrations.DeleteModel(
            name='GFWInboundConfiguration',
        ),
        migrations.AlterModelOptions(
            name='inboundintegrationconfiguration',
            options={'ordering': ('owner', 'name')},
        ),
        migrations.AlterModelOptions(
            name='outboundintegrationconfiguration',
            options={'ordering': ('owner', 'name')},
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='destinations',
            field=models.ManyToManyField(blank=True, help_text='Outbound Integration(s). To choose multiple options, hold CMD/Ctrl key and select.', related_name='devicegroups', related_query_name='devicegroup', to='integrations.OutboundIntegrationConfiguration'),
        ),
        migrations.DeleteModel(
            name='HistoricalGFWInboundConfiguration',
        ),
    ]
