# Generated by Django 3.2.15 on 2023-04-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0053_auto_20230331_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutboundintegrationtype',
            name='dest_configuration_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='JSON Schema for configuration value'),
        ),
        migrations.AddField(
            model_name='outboundintegrationtype',
            name='dest_configuration_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='JSON Schema for configuration value'),
        ),
    ]
