# Generated by Django 3.2.15 on 2023-04-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0054_auto_20230404_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloutboundintegrationtype',
            name='dest_configuration_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='JSON Schema for destination configuration'),
        ),
        migrations.AlterField(
            model_name='outboundintegrationtype',
            name='dest_configuration_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='JSON Schema for destination configuration'),
        ),
    ]
