# Generated by Django 3.2.15 on 2023-04-25 19:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0056_integrationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Type')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug Identifier')),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(blank=True, default=dict, verbose_name='JSON Schema')),
                ('integration_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='integrations.integrationtype', verbose_name='Integration Type')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
