# Generated by Django 3.2.15 on 2023-05-02 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0059_integrationconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='JSON State')),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='integrations.integration')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
