# Generated by Django 3.2.15 on 2023-05-02 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0060_integrationstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRuleType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(blank=True, default=dict, verbose_name='JSON Schema')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
