# Generated by Django 3.2.15 on 2023-04-25 19:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_ordering'),
        ('integrations', '0061_routingruletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source_selector', models.JSONField(blank=True, default=dict, verbose_name='JSON Selector')),
                ('additional', models.JSONField(blank=True, default=dict, verbose_name='Additional JSON Configuration')),
                ('destinations', models.ManyToManyField(blank=True, help_text='Destination Integrations where the data will be delivered.', related_name='routing_rules', to='integrations.Integration')),
                ('owner', models.ForeignKey(help_text='Organization that owns the data.', on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules_by_owner', to='organizations.organization')),
                ('type', models.ForeignKey(help_text='The type of routing rule.', on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules_by_type', to='integrations.routingruletype', verbose_name='Type')),
            ],
            options={
                'ordering': ('owner', 'name'),
            },
        ),
    ]
