# Generated by Django 3.2.15 on 2023-05-02 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_ordering'),
        ('integrations', '0062_routingruleconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source_filter', models.JSONField(blank=True, default=dict, verbose_name='JSON Filter')),
                ('additional', models.JSONField(blank=True, default=dict, verbose_name='Additional JSON Configuration')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules_by_configuration', to='integrations.routingruleconfiguration', verbose_name='Routing Rule Configuration')),
                ('data_providers', models.ManyToManyField(blank=True, related_name='routing_rules_by_provider', to='integrations.Integration', verbose_name='Data Providers')),
                ('destinations', models.ManyToManyField(blank=True, related_name='routing_rules_by_destination', to='integrations.Integration', verbose_name='Destinations')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules_by_owner', to='organizations.organization', verbose_name='Owner')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules_by_type', to='integrations.routingruletype', verbose_name='Routing Rule Type')),
            ],
            options={
                'ordering': ('owner', 'name'),
            },
        ),
    ]
