# Generated by Django 3.2.15 on 2023-05-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0063_routingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='default_routing_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integrations_by_rule', to='integrations.routingrule', verbose_name='Default Routing Rule'),
        ),
    ]
