# Generated by Django 3.2.15 on 2023-04-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0063_integration_default_routing_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationaction',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
