# Generated by Django 3.2.15 on 2023-05-02 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0066_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='JSON State')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='integrations.source')),
            ],
            options={
                'ordering': ('source', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='sourcestate',
            index=models.Index(fields=['source', 'created_at'], name='integration_source__e16379_idx'),
        ),
    ]
