# Generated by Django 3.2.15 on 2023-04-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0067_rename_slug_integrationaction_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationaction',
            name='value',
            field=models.SlugField(max_length=200, verbose_name='Value (Identifier)'),
        ),
    ]
