# Generated by Django 3.2.15 on 2023-04-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0068_alter_integrationaction_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrationtype',
            old_name='slug',
            new_name='value',
        ),
    ]
