# Generated by Django 3.2.15 on 2023-05-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0069_remove_routingrule_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoutingRuleType',
        ),
    ]
