# Generated by Django 3.2.15 on 2023-04-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0070_alter_integrationtype_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingrule',
            name='destinations',
            field=models.ManyToManyField(blank=True, help_text='Destination Integrations where the data will be delivered.', related_name='routing_rules_by_destination', to='integrations.Integration'),
        ),
    ]
