# Generated by Django 3.2.15 on 2023-05-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0070_delete_routingruletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routingrule',
            name='source_filter',
        ),
    ]
