# Generated by Django 3.2.15 on 2023-04-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0071_alter_routingrule_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingrule',
            name='sources',
            field=models.ManyToManyField(blank=True, help_text='Source Integrations where the data is extracted from', related_name='routing_rules_by_source', to='integrations.Integration'),
        ),
    ]
