# Generated by Django 3.2.15 on 2023-04-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0072_routingrule_sources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routingrule',
            old_name='sources',
            new_name='data_providers',
        ),
    ]
