# Generated by Django 3.2.15 on 2023-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0073_alter_sourcefilter_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['integration', 'external_id'], name='integration_integra_0880de_idx'),
        ),
    ]
