# Generated by Django 3.2.15 on 2023-04-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0073_rename_sources_routingrule_data_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingrule',
            name='data_providers',
            field=models.ManyToManyField(blank=True, help_text='Source Integrations where the data is extracted from', related_name='routing_rules_by_provider', to='integrations.Integration'),
        ),
    ]
