# Generated by Django 3.2.15 on 2023-05-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0074_source_integration_integra_0880de_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources_by_configuration', to='integrations.sourceconfiguration', verbose_name='Source Configuration'),
        ),
    ]
