# Generated by Django 3.2.15 on 2023-04-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0074_alter_routingrule_data_providers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routingrule',
            old_name='source_selector',
            new_name='source_filter',
        ),
    ]
