# Generated by Django 3.2.15 on 2023-04-28 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0076_sourceconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('external_id', models.CharField(help_text='Id sent by the data provider', max_length=200)),
                ('additional', models.JSONField(blank=True, default=dict, help_text='Additional config(s)')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources_by_configuration', to='integrations.source')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources_by_integration', to='integrations.integration')),
            ],
            options={
                'ordering': ('integration', 'external_id'),
                'unique_together': {('integration', 'external_id')},
            },
        ),
    ]
