# Generated by Django 3.2.15 on 2023-05-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_ordering'),
        ('integrations', '0076_alter_source_external_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoutingRule',
            new_name='Route',
        ),
    ]
