# Generated by Django 3.2.15 on 2023-05-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0077_rename_routingrule_route'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoutingRuleConfiguration',
            new_name='RouteConfiguration',
        ),
    ]
