# Generated by Django 3.2.15 on 2023-05-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0078_rename_routingruleconfiguration_routeconfiguration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integration',
            old_name='default_routing_rule',
            new_name='default_route',
        ),
    ]
