# Generated by Django 3.2.15 on 2023-05-01 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0079_alter_source_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRuleConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='JSON Configuration')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
