# Generated by Django 3.2.15 on 2023-06-08 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0080_alter_route_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GundiTrace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('delivered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=250)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_by_user', to=settings.AUTH_USER_MODEL)),
                ('data_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects_by_provider', to='integrations.integration')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_by_destination', to='integrations.integration')),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_objects', to='integrations.gunditrace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='gunditrace',
            index=models.Index(fields=['created_at'], name='integration_created_de91ab_idx'),
        ),
        migrations.AddIndex(
            model_name='gunditrace',
            index=models.Index(fields=['updated_at'], name='integration_updated_8bd86e_idx'),
        ),
    ]
