# Generated by Django 3.2.15 on 2023-07-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0083_alter_gunditrace_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunditrace',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
