# Generated by Django 3.2.15 on 2023-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0085_alter_gunditrace_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunditrace',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
