# Generated by Django 3.2.15 on 2023-10-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0086_alter_gunditrace_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunditrace',
            name='error',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gunditrace',
            name='has_error',
            field=models.BooleanField(default=False),
        ),
    ]
