# Generated by Django 3.2.15 on 2023-10-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0087_auto_20231019_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunditrace',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
