# Generated by Django 3.2.15 on 2023-10-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0088_gunditrace_is_duplicate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationconfiguration',
            options={'ordering': ('-updated_at',)},
        ),
    ]
