# Generated by Django 3.2.15 on 2023-10-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0089_alter_integrationconfiguration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationaction',
            name='is_periodic_action',
            field=models.BooleanField(default=False),
        ),
    ]
