# Generated by Django 3.2.15 on 2023-11-06 19:57

import activity_log.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0091_routeprovider'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE integrations_route_destinations RENAME TO integrations_routedestination",
                    reverse_sql="ALTER TABLE integrations_routedestination RENAME TO integrations_route_destinations",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='RouteDestination',
                    fields=[
                        ("id",
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('integration',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
                        ('route',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.route')),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=(activity_log.mixins.ChangeLogMixin, models.Model),
                ),
                migrations.AlterField(
                    model_name='route',
                    name='destinations',
                    field=models.ManyToManyField(
                        blank=True,
                        related_name='routing_rules_by_destination',
                        through='integrations.RouteDestination',
                        to='integrations.Integration',
                        verbose_name='Destinations',
                    ),
                ),
            ],
        ),
    ]
