# Generated by Django 3.2.15 on 2023-12-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0092_routedestination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='default_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations_by_rule', to='integrations.route', verbose_name='Default Routing Rule'),
        ),
    ]
