# Generated by Django 3.2.25 on 2024-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0094_integrationconfiguration_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationtype',
            name='actions_endpoint',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
