# Generated by Django 3.2.25 on 2024-04-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0095_integrationtype_actions_endpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrationtype',
            old_name='actions_endpoint',
            new_name='service_url',
        ),
    ]
