# Generated by Django 3.2.25 on 2024-07-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0098_webhookconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunditrace',
            name='object_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
