# Generated by Django 3.2.25 on 2024-07-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0099_gunditrace_object_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunditrace',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_by_source', to='integrations.source'),
        ),
    ]
