# Generated by Django 3.2.25 on 2024-07-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0100_gunditrace_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunditrace',
            name='last_update_delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
