# Generated by Django 3.2.25 on 2024-10-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0101_gunditrace_last_update_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationaction',
            name='ui_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='UI Schema'),
        ),
    ]
