# Generated by Django 3.2.25 on 2024-10-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0105_integrationstatus_status_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationstatus',
            options={'ordering': ('-updated_at',), 'verbose_name_plural': 'Integration statuses'},
        ),
    ]
