# Generated by Django 3.2.25 on 2024-10-30 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0106_alter_integrationstatus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_count_threshold', models.PositiveIntegerField(default=3)),
                ('time_window_minutes', models.PositiveIntegerField(default=60)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_check_settings', to='integrations.integration')),
            ],
            options={
                'verbose_name_plural': 'Integration health check settings',
                'ordering': ('-updated_at',),
            },
        ),
    ]
