# Generated by Django 3.2.25 on 2024-10-30 20:23

from django.db import migrations


def create_healthcheck_schedule(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    # Get or create periodic task to run every hour
    schedule, created = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="*",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
    )
    PeriodicTask.objects.get_or_create(
        task="integrations.tasks.calculate_integration_statuses_in_batches",
        defaults={
            "crontab": schedule,
            "name": "Calculate Integration Statuses",
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0107_healthchecksettings'),
    ]

    operations = [
        migrations.RunPython(create_healthcheck_schedule),
    ]
