# Generated by Django 3.2.25 on 2024-10-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0108_healthchecks_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationstatus',
            name='status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('disabled', 'Disabled')], db_index=True, default='healthy', max_length=20),
        ),
    ]
