# Generated by Django 3.2.25 on 2024-12-16 12:39

from django.db import migrations


def create_status_email_schedule(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    # Get or create periodic task to run once a day
    schedule, created = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="6",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
    )
    PeriodicTask.objects.get_or_create(
        task="integrations.tasks.send_unhealthy_connections_email",
        defaults={
            "crontab": schedule,
            "name": "Send unhealthy connections email alert",
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0108_healthchecks_schedule'),
    ]

    operations = [
        migrations.RunPython(create_status_email_schedule, reverse_code=migrations.RunPython.noop),
    ]
