# Generated by Django 3.2.25 on 2024-12-19 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('integrations', '0109_status_email_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationaction',
            name='crontab_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_by_crontab_schedule', to='django_celery_beat.crontabschedule'),
        ),
    ]
