# Generated by Django 3.2.25 on 2025-01-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0110_integrationaction_crontab_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationaction',
            options={'ordering': ('order_number', 'name')},
        ),
        migrations.AddField(
            model_name='integrationaction',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='integrationaction',
            name='tags',
            field=models.JSONField(blank=True, default=dict, help_text='JSON list of tags for the action', verbose_name='Tags'),
        ),
    ]
