# Generated by Django 3.2.25 on 2025-01-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0111_auto_20250124_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationaction',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of tags for the action', verbose_name='Tags'),
        ),
    ]
