# Generated by Django 3.2.25 on 2025-02-06 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0111_integrationtype_help_center_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationMetrics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_frequency_minutes', models.PositiveIntegerField(default=0)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='integrations.integration')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
