# Generated by Django 3.2.25 on 2025-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0113_metrics_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationmetrics',
            name='data_frequency_minutes_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='integrationmetrics',
            name='data_frequency_minutes_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
