# Generated by Django 4.2.24 on 2026-07-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0115_integrationconfiguration_unique_integration_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthchecksettings',
            name='retriable_error_count_threshold',
            field=models.PositiveIntegerField(default=30, help_text='Number of retriable (warning-level) delivery failures within the time window before the integration is marked unhealthy. Retriable failures are transient destination errors that PubSub retries; a sustained volume indicates an outage.'),
        ),
    ]
