# Generated by Django 4.2.24 on 2026-08-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0116_healthchecksettings_retriable_error_count_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationaction',
            name='type',
            field=models.CharField(choices=[('auth', 'Authentication'), ('pull', 'Pull Data'), ('push', 'Push Data'), ('generic', 'Generic Action'), ('reference', 'Reference Data')], default='generic', max_length=20),
        ),
    ]
