# Generated by Django 4.2.24 on 2026-09-18 22:46

from django.db import migrations, models
import integrations.models.v2.default_route


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0117_alter_integrationaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='default_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=integrations.models.v2.default_route.reassign_default_route, related_name='integrations_by_rule', to='integrations.route', verbose_name='Default Routing Rule'),
        ),
    ]
