# Generated by Django 4.2.24 on 2026-10-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0118_integration_default_route_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunditrace',
            name='discard_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='gunditrace',
            name='discarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
