# Generated by Django 4.2.24 on 2026-09-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0118_sourcefilter_device_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunditrace',
            name='filtered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='gunditrace',
            name='filtered_by',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='gunditrace',
            name='is_filtered',
            field=models.BooleanField(default=False),
        ),
    ]
