# Generated by Django 4.2.24 on 2026-09-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0119_sourcefilter_device_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='created_via',
            field=models.CharField(choices=[('ingestion', 'Discovered by the integration'), ('manual', 'Created by a user')], default='ingestion', max_length=20),
        ),
    ]
