# Generated by Django 4.2.24 on 2026-10-01 18:36

from django.db import migrations, models


def backfill_covered_providers(apps, schema_editor):
    # Scope starts as the providers of the sources each rule currently names;
    # from here on, API writes maintain it and cascades leave it alone.
    SourceFilter = apps.get_model("integrations", "SourceFilter")
    for source_filter in SourceFilter.objects.prefetch_related("sources"):
        provider_ids = {
            source.integration_id for source in source_filter.sources.all()
        }
        if provider_ids:
            source_filter.covered_providers.set(provider_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0120_source_created_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefilter',
            name='covered_providers',
            field=models.ManyToManyField(blank=True, related_name='source_filters_covering_provider', to='integrations.integration', verbose_name='Covered Providers'),
        ),
        migrations.RunPython(
            backfill_covered_providers, migrations.RunPython.noop
        ),
    ]
