# Generated by Django 4.2.24 on 2026-10-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0121_sourcefilter_covered_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefilter',
            name='mode',
            field=models.CharField(max_length=20),
        ),
    ]
