# Generated by Django 3.1 on 2021-07-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_apiconsumer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "managed": False,
                "permissions": [("admin", "Admin Role"), ("viewer", "Viewer Role")],
            },
        ),
    ]
