# Generated by Django 3.1.5 on 2021-10-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210730_1729"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "permissions": [("admin", "Admin Role"), ("viewer", "Viewer Role")]
            },
        ),
    ]
