namespace = "cdip-prod01"
functions-namespace = "cdip-functions-prod01"
metrics-namespace = "metrics"
site-fqdn = "cdip-prod01.pamdas.org"
airflow-fqdn = "airflow-prod01.pamdas.org"
api-fqdn = "cdip-api-prod01.pamdas.org"
realm-suffix = "-prod"
airflow-gcs-logs-folder = "gs://cdip-78ca-airflow-prod-logs"