namespace = "cdip-v1"
functions-namespace = "cdip-functions"
metrics-namespace = "metrics"
site-fqdn = "cdip-dev.pamdas.org"
airflow-fqdn = "airflow.pamdas.org"
api-fqdn = "cdip-api.pamdas.org"
realm-suffix = "-dev"
airflow-gcs-logs-folder = "gs://cdip-78ca-airflow-dev-logs"