namespace = "cdip-v1"
functions-namespace = "cdip-functions"
metrics-namespace = "metrics"
site-fqdn = "cdip-dev.pamdas.org"
airflow-fqdn = "airflow.pamdas.org"
api-fqdn = "cdip-api.pamdas.org"
realm-suffix = "-dev"
airflow-gcs-logs-folder = "gs://airflow-dev-logs"
//allowed-hosts = ["cdip-dev.pamdas.org", "34.107.179.120"]