# Generated by Django 3.1 on 2021-04-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accountprofileorganization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofileorganization",
            name="role",
            field=models.CharField(
                choices=[("admin", "admin"), ("viewer", "viewer")],
                default="viewer",
                max_length=200,
            ),
        ),
    ]
