# Generated by Django 3.2 on 2021-06-08 02:08

import core.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0008_accountprofile_uniq_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountprofile",
            name="user_username",
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="accountprofileorganization",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="accountprofileorganization",
            name="role",
            field=models.CharField(
                choices=[("admin", "admin"), ("viewer", "viewer")],
                default=core.enums.RoleChoices["VIEWER"],
                max_length=200,
            ),
        ),
    ]
