# Generated by Django 3.2.25 on 2024-05-03 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_accountprofileorganization_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EULA',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=30, unique=True)),
                ('eula_url', models.URLField()),
                ('active', models.BooleanField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
