# Generated by Django 3.2.25 on 2024-05-03 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_eula'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_accepted', models.DateTimeField(auto_now_add=True, verbose_name='Date Accepted')),
                ('accept', models.BooleanField(default=False)),
                ('eula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userterms', to='accounts.eula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userterms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'eula')},
            },
        ),
    ]
