# Generated by Django 3.2.25 on 2024-05-03 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_useragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='eula',
            name='users',
            field=models.ManyToManyField(blank=True, through='accounts.UserAgreement', to=settings.AUTH_USER_MODEL),
        ),
    ]
