# Generated by Django 3.2.25 on 2024-05-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_eula_users'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eula',
            constraint=models.UniqueConstraint(fields=('active',), name='unique_active_eula'),
        ),
    ]
