# Generated by Django 3.2.25 on 2024-05-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_eula_unique_active_eula'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='accepted_eula',
            field=models.BooleanField(default=False),
        ),
    ]
