serviceAccount: admin-portal-sa@cdip-dev-78ca.iam.gserviceaccount.com
ingress:
  hosts:
    - host: "api.dev.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: admin-portal
    - host: "sensors.api.dev.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: admin-portal-sensors
  tls:
    - secretName: "admin-portal-tls"
      hosts:
        - "api.dev.gundiservice.org"
        - "sensors.api.dev.gundiservice.org"
database:
  private_ip_enabled: True
  connection_name: cdip-dev-78ca:us-central1:sintegrate-b2b9960e
admin_portal:
  env:
    TRACE_ENVIRONMENT: "dev"
    BROKER_URL: "redis://10.3.176.132:6379"
    GCP_PROJECT_ID: cdip-dev-78ca
    DISPATCHER_EVENTS_SUB_ID: cdip-dispatcher-events-sub-dev
    REDIS_HOST: "10.3.176.132"
    GS_BUCKET_NAME: "cdip-files-dev"
    BUCKET_NAME: "cdip-files-dev"
    DISPATCHER_DEFAULTS_SECRET: "er-dispatcher-defaults-dev"
    MOVEBANK_DISPATCHER_DEFAULT_TOPIC: "destination-movebank-dev"
    DISPATCHER_DEFAULTS_SECRET_SMART: "sm-dispatcher-defaults-dev"
    INTEGRATION_EVENTS_SUB_ID: cdip-integration-events-sub-dev
    RAW_OBSERVATIONS_TOPIC: raw-observations-dev
    DISPATCHER_DEFAULTS_SECRET_WPSWATCH: wps-dispatcher-defaults-dev
    PORTAL_BASE_URL: "https://dev.gundiservice.org"
kongplugin:
  cors:
    - https://dev.gundiservice.org
    - https://api.dev.gundiservice.org
keycloak:
  KEYCLOAK_SERVER: "https://cdip-auth.pamdas.org"
  KEYCLOAK_REALM: "cdip-dev"
  KEYCLOAK_ADMIN_REALM: "cdip-dev"
  KEYCLOAK_CLIENT_ID: "cdip-admin-portal"
  KEYCLOAK_ADMIN_CLIENT_ID: admin-cli
portal:
  resources:
    requests:
      cpu: 600m
      memory: 1000Mi
