ingress:
  hosts:
    - host: "admin.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: "admin-portal-tls"
      hosts:
        - "admin.gundiservice.org"
database:
  connection_name: "cdip-stage-78ca:us-central1:sintegrate-5bbf9d1f"
keycloak:
  KEYCLOAK_SERVER: "https://cdip-auth.pamdas.org"
  KEYCLOAK_REALM: "cdip-dev"
  KEYCLOAK_ADMIN_REALM: "cdip-dev"
  KEYCLOAK_CLIENT_ID: "cdip-admin-portal"
  KEYCLOAK_ADMIN_CLIENT_ID: admin-cli
