serviceAccount: gundi-app-sa-4bb07e9c@cdip-prod1-78ca.iam.gserviceaccount.com
ingress:
  hosts:
    - host: "api.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: admin-portal
    - host: "sensors.api.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: admin-portal-sensors
  tls:
    - secretName: "admin-portal-tls"
      hosts:
        - "api.gundiservice.org"
        - "sensors.api.gundiservice.org"
celery:
  worker:
    replicaCount: 2
eventsConsumer:
  replicaCount: 2
database:
  connection_name: "cdip-78ca:us-central1:postgres-cdip-prod01"
admin_portal:
  env:
    TRACE_ENVIRONMENT: "prod"
    BROKER_URL: "redis://10.208.106.172:6379"
    GCP_PROJECT_ID: cdip-prod1-78ca
    DISPATCHER_EVENTS_SUB_ID: cdip-dispatcher-events-sub-prod
    REDIS_HOST: "10.208.106.172"
    GS_BUCKET_NAME: "cdip-files-prod"
    DISPATCHER_DEFAULTS_SECRET: "er-dispatcher-defaults-prod"
    MOVEBANK_DISPATCHER_DEFAULT_TOPIC: "movebank-events-prod"
kongplugin:
  cors:
    - https://gundiservice.org
    - https://api.gundiservice.org
keycloak:
  KEYCLOAK_SERVER: "https://cdip-auth.pamdas.org"
  KEYCLOAK_REALM: "cdip-prod"
  KEYCLOAK_ADMIN_REALM: "cdip-prod"
  KEYCLOAK_CLIENT_ID: "cdip-admin-portal"
  KEYCLOAK_ADMIN_CLIENT_ID: admin-cli
replicaCount: 2