serviceAccount: admin-portal-sa@cdip-prod1-78ca.iam.gserviceaccount.com
ingress:
  hosts:
    - host: "api.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: admin-portal
    - host: "sensors.api.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: admin-portal-sensors
  tls:
    - secretName: "admin-portal-tls"
      hosts:
        - "api.gundiservice.org"
        - "sensors.api.gundiservice.org"
celery:
  worker:
    replicaCount: 2
eventsConsumer:
  replicaCount: 2
database:
  connection_name: "cdip-78ca:us-central1:postgres-cdip-prod01"
admin_portal:
  env:
    LOGGING_LEVEL: "INFO"
    TRACE_ENVIRONMENT: "prod"
    BROKER_URL: "redis://10.208.106.172:6379"
    GCP_PROJECT_ID: cdip-prod1-78ca
    DISPATCHER_EVENTS_SUB_ID: cdip-dispatcher-events-sub-prod
    REDIS_HOST: "10.208.106.172"
    GS_BUCKET_NAME: "cdip-files-prod"
    BUCKET_NAME: "cdip-files-prod"
    DISPATCHER_DEFAULTS_SECRET: "er-dispatcher-defaults-prod"  # pragma: allowlist secret
    MOVEBANK_DISPATCHER_DEFAULT_TOPIC: "destination-movebank-prod"
    DISPATCHER_DEFAULTS_SECRET_SMART: "sm-dispatcher-defaults-prod"  # pragma: allowlist secret
    DISPATCHER_DEFAULTS_SECRET_WPSWATCH: "wps-dispatcher-defaults-prod"  # pragma: allowlist secret
    DISPATCHER_DEFAULTS_SECRET_TRAPTAGGER: "tt-dispatcher-defaults-prod"  # pragma: allowlist secret
    INTEGRATION_EVENTS_SUB_ID: cdip-integration-events-sub-prod
    RAW_OBSERVATIONS_TOPIC: raw-observations-prod
    PORTAL_BASE_URL: "https://gundiservice.org"
    CONFIGURATION_EVENTS_TOPIC: "configuration-events-prod"
    EMAIL_INVITE_REDIRECT_URL: "https://gundiservice.org"
kongplugin:
  cors:
    - https://gundiservice.org
    - https://api.gundiservice.org
keycloak:
  KEYCLOAK_SERVER: "https://cdip-auth.pamdas.org"
  KEYCLOAK_REALM: "cdip-prod"
  KEYCLOAK_ADMIN_REALM: "cdip-prod"
  KEYCLOAK_CLIENT_ID: "cdip-admin-portal"
  KEYCLOAK_ADMIN_CLIENT_ID: admin-cli

portal:
  resources:
    requests:
      cpu: 600m
      memory: 1000Mi
  autoscaling:
    enabled: true
    minReplicas: 4
    maxReplicas: 20
    targetCPUUtilizationPercentage: 80
worker:
  replicaCount: 2
dispatcherEvents:
  replicaCount: 2
integrationEvents:
  replicaCount: 2
deploymentsWorker:
  replicaCount: 2
