serviceAccount: cloudsqlproxy-4bb07e9c@cdip-prod1-78ca.iam.gserviceaccount.com
ingress:
  hosts:
    - host: "admin.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: "admin-portal-tls"
      hosts:
        - "admin.gundiservice.org"
database:
  connection_name: "cdip-prod1-78ca:us-central1:sintegrate-4bb07e9c"
admin_portal:
  env:
    BROKER_URL: "redis://10.208.106.172:6379"
kongplugin:
  cors:
    - https://gundiservice.org