serviceAccount: gundi-app-sa-5bbf9d1f@cdip-stage-78ca.iam.gserviceaccount.com
ingress:
  hosts:
    - host: "admin.stage.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: "admin-portal-tls"
      hosts:
        - "admin.stage.gundiservice.org"
database:
  connection_name: "cdip-stage-78ca:us-central1:sintegrate-5bbf9d1f"
admin_portal:
  env:
    TRACE_ENVIRONMENT: "stage"
    BROKER_URL: "redis://10.243.180.36:6379"
    GCP_PROJECT_ID: cdip-stage-78ca
kongplugin:
  cors:
    - https://stage.gundiservice.org
    - https://admin.stage.gundiservice.org
keycloak:
  KEYCLOAK_SERVER: "https://cdip-auth.pamdas.org"
  KEYCLOAK_REALM: "cdip-dev"
  KEYCLOAK_ADMIN_REALM: "cdip-dev"
  KEYCLOAK_CLIENT_ID: "***REMOVED***"
  KEYCLOAK_ADMIN_CLIENT_ID: ***REMOVED***