serviceAccount: cloudsqlproxy-5bbf9d1f@cdip-stage-78ca.iam.gserviceaccount.com
ingress:
  hosts:
    - host: "admin.stage.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: "admin-portal-tls"
      hosts:
        - "admin.stage.gundiservice.org"
database:
  connection_name: "cdip-stage-78ca:us-central1:sintegrate-5bbf9d1f"
admin_portal:
  env:
    BROKER_URL: "redis://10.243.180.36:6379"
kongplugin:
  cors:
    - https://gundiservice.org