serviceAccount: gundi-app-sa-5bbf9d1f@cdip-stage-78ca.iam.gserviceaccount.com
ingress:
  hosts:
    - host: "admin.stage.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: admin-portal
    - host: "sensors.api.stage.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: admin-portal-sensors
  tls:
    - secretName: "admin-portal-tls"
      hosts:
        - "admin.stage.gundiservice.org"
        - "sensors.api.stage.gundiservice.org"
celery:
  worker:
    replicaCount: 2
eventsConsumer:
  replicaCount: 1
database:
  connection_name: "cdip-78ca:us-central1:postgres-cdip-dev"
admin_portal:
  env:
    TRACE_ENVIRONMENT: "stage"
    BROKER_URL: "redis://10.243.180.36:6379"
    GCP_PROJECT_ID: cdip-stage-78ca
    DISPATCHER_EVENTS_SUB_ID: cdip-dispatcher-events-sub-stage
    REDIS_HOST: "10.243.180.36"
    GS_BUCKET_NAME: "cdip-files-stage"
kongplugin:
  cors:
    - https://stage.gundiservice.org
    - https://admin.stage.gundiservice.org
keycloak:
  KEYCLOAK_SERVER: "https://cdip-auth.pamdas.org"
  KEYCLOAK_REALM: "cdip-dev"
  KEYCLOAK_ADMIN_REALM: "cdip-dev"
  KEYCLOAK_CLIENT_ID: "***REMOVED***"
  KEYCLOAK_ADMIN_CLIENT_ID: ***REMOVED***
replicaCount: 2