serviceAccount: admin-portal-sa@cdip-stage-78ca.iam.gserviceaccount.com
ingress:
  hosts:
    - host: "api.stage.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: admin-portal
    - host: "sensors.api.stage.gundiservice.org"
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: admin-portal-sensors
  tls:
    - secretName: "admin-portal-tls"
      hosts:
        - "api.stage.gundiservice.org"
        - "sensors.api.stage.gundiservice.org"
database:
  connection_name: "cdip-78ca:us-central1:postgres-cdip-dev"
admin_portal:
  env:
    LOGGING_LEVEL: "INFO"
    TRACE_ENVIRONMENT: "stage"
    BROKER_URL: "redis://10.243.180.36:6379"
    GCP_PROJECT_ID: cdip-stage-78ca
    DISPATCHER_EVENTS_SUB_ID: cdip-dispatcher-events-sub-stage
    REDIS_HOST: "10.243.180.36"
    GS_BUCKET_NAME: "cdip-files-stage"
    DISPATCHER_DEFAULTS_SECRET: "er-dispatcher-defaults-stage"
    MOVEBANK_DISPATCHER_DEFAULT_TOPIC: "destination-movebank-stage"
    DISPATCHER_DEFAULTS_SECRET_SMART: "sm-dispatcher-defaults-stage"
    INTEGRATION_EVENTS_SUB_ID: cdip-integration-events-sub-stage
    RAW_OBSERVATIONS_TOPIC: raw-observations-stage
    DISPATCHER_DEFAULTS_SECRET_WPSWATCH: wps-dispatcher-defaults-stage
kongplugin:
  cors:
    - https://stage.gundiservice.org
    - https://api.stage.gundiservice.org
keycloak:
  KEYCLOAK_SERVER: "https://cdip-auth.pamdas.org"
  KEYCLOAK_REALM: "cdip-dev"
  KEYCLOAK_ADMIN_REALM: "cdip-dev"
  KEYCLOAK_CLIENT_ID: "cdip-admin-portal"
  KEYCLOAK_ADMIN_CLIENT_ID: admin-cli

portal:
  replicaCount: 2
worker:
  replicaCount: 2