# Generated by Django 3.2.15 on 2023-11-03 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0090_integrationaction_is_periodic_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_level', models.IntegerField(choices=[(0, 'Debug'), (1, 'Info'), (2, 'Warning'), (3, 'Error')], db_index=True, default=1)),
                ('log_type', models.CharField(choices=[('cdc', 'Data Change'), ('ev', 'Event')], db_index=True, max_length=5)),
                ('origin', models.CharField(choices=[('port', 'Portal'), ('inte', 'Integration'), ('tran', 'Transformer'), ('disp', 'Dispatcher')], db_index=True, max_length=5)),
                ('value', models.SlugField(max_length=40, verbose_name='Value (Identifier)')),
                ('title', models.CharField(max_length=200)),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='JSON Details')),
                ('is_reversible', models.BooleanField(default=False)),
                ('revert_data', models.JSONField(blank=True, default=dict, verbose_name='JSON Revert Details')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_by_user', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_by_integration', to='integrations.integration')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
