# Generated by Django 3.2.15 on 2023-11-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='activity_lo_created_14fffc_idx'),
        ),
    ]
