# Generated by Django 3.2.15 on 2023-11-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0092_routedestination'),
        ('activity_log', '0002_activitylog_activity_lo_created_14fffc_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_by_integration', to='integrations.integration'),
        ),
    ]
