# Generated by Mariano. Django 3.2.15 on 2024-10-23 17:46

from django.db import migrations, models

CREATE_INDEX_SQL = sql = "CREATE INDEX IF NOT EXISTS {index_name} ON {table_name} ({columns});"
DROP_INDEX_SQL = "DROP INDEX IF EXISTS {index_name};"

model_name = "activity_log_activitylog"

class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_alter_activitylog_integration'),
    ]

    operations = [
        # Add indexes on partitioning columns
        migrations.RunSQL(
            sql=CREATE_INDEX_SQL.format(
                index_name="activity_log_log_type_idx",
                table_name=model_name,
                columns="log_type",
            ),
            reverse_sql=DROP_INDEX_SQL.format(index_name="activity_log_log_type_idx"),
        ),
        migrations.RunSQL(
            sql=CREATE_INDEX_SQL.format(
                index_name="activity_log_created_at_idx",
                table_name=model_name,
                columns="created_at DESC",
            ),
            reverse_sql=DROP_INDEX_SQL.format(index_name="activity_log_created_at_idx"),
        ),
        # ToDo: Restore other indexes lost during partitioning
    ]
