# Generated by Django 3.2.15 on 2023-07-18 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0085_alter_gunditrace_related_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherDeployment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('sch', 'Deployment Scheduled'), ('pro', 'Deployment In Progress'), ('err', 'Deployment Failed'), ('com', 'Deployment Complete')], default='sch', max_length=20)),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='JSON Configuration')),
                ('integration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatcher_by_integration', to='integrations.integration', verbose_name='Destination Integration')),
                ('legacy_integration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatcher_by_outbound', to='integrations.outboundintegrationconfiguration', verbose_name='Destination Integration')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
