# Generated by Django 3.2.15 on 2023-08-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_alter_dispatcherdeployment_legacy_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherdeployment',
            name='status',
            field=models.CharField(choices=[('sch', 'Deployment Scheduled'), ('pro', 'Deployment In Progress'), ('err', 'Deployment Failed'), ('com', 'Deployment Complete'), ('del', 'Deleting')], default='sch', max_length=20),
        ),
    ]
