# Generated by Django 3.2.15 on 2023-08-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_auto_20230808_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherdeployment',
            name='status',
            field=models.CharField(choices=[('sch', 'Deployment Scheduled'), ('pro', 'Deployment In Progress'), ('err', 'Failed'), ('com', 'Deployment Complete'), ('del', 'Deleting')], default='sch', max_length=20),
        ),
    ]
