name: Build and deploy admin-portal
on:
  push:
    branches:
      - main
      - 'release-**'
      - gundi-4008-data-frequency-metric
env:
  TRACING_ENABLED: ${{secrets.TRACING_ENABLED}}
  PUBSUB_ENABLED: ${{secrets.PUBSUB_ENABLED}}
  CELERY_TASK_ALWAYS_EAGER: ${{secrets.CELERY_TASK_ALWAYS_EAGER}}
jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      repository: ${{ steps.vars.outputs.repository }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          echo "tag=${{ github.head_ref || github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repository=us-central1-docker.pkg.dev/cdip-78ca/gundi/admin-portal" >> $GITHUB_OUTPUT

  build:
    uses: PADAS/gundi-workflows/.github/workflows/build_docker.yml@v2
    needs: vars
    with:
      environment: stage
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}

  deploy_dev:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v2
    if: startsWith(github.ref, 'refs/heads/gundi-4008-data-frequency-metric')
    needs: [vars, build]
    with:
      environment: dev
      chart_name: admin-portal
      chart_version: '1.3.1'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
    secrets: inherit

  deploy_stage:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v2
    if: startsWith(github.ref, 'refs/heads/release')
    needs: [vars, build]
    with:
      environment: stage
      chart_name: admin-portal
      chart_version: '1.3.1'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
    secrets: inherit

  deploy_dev_legacy:
    uses: PADAS/gundi-workflows/.github/workflows/update_k8s_image.yml@v2
    if: startsWith(github.ref, 'refs/heads/release')
    needs: [vars, build]
    strategy:
      matrix:
        deployment: 
          - cdip-portal
          - celery-beat
          - celery-deployments-worker
          - celery-permissions-worker
          - celery-worker
    with:
      environment: dev-legacy
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
      deployment: ${{ matrix.deployment }}
      container: main
      namespace: cdip-v1
    secrets: inherit

  deploy_prod:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v2
    if: startsWith(github.ref, 'refs/heads/release')
    needs: [vars, build, deploy_stage]
    with:
      environment: prod
      chart_name: admin-portal
      chart_version: '1.3.1'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
    secrets: inherit

  deploy_prod_legacy:
    uses: PADAS/gundi-workflows/.github/workflows/update_k8s_image.yml@v2
    if: startsWith(github.ref, 'refs/heads/release')
    needs: [vars, build, deploy_stage]
    strategy:
      matrix:
        deployment: 
          - cdip-portal
          - celery-beat
          - celery-deployments-worker
          - celery-permissions-worker
          - celery-worker
    with:
      environment: prod-legacy
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
      deployment: ${{ matrix.deployment }}
      container: main
      namespace: cdip-prod01
    secrets: inherit
