name: Build and deploy admin-portal
on:
  push:
    branches:
      - SIK-2015

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
      repository: ${{ steps.vars.outputs.repository }}
    steps:
      - uses: actions/checkout@v3
      - id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repository=us-central1-docker.pkg.dev/cdip-78ca/gundi/admin-portal" >> $GITHUB_OUTPUT

  build:
    uses: ./.github/workflows/_build.yml
    needs: vars
    with:
      environment: stage
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.sha_short }}

  deploy_stage:
    uses: ./.github/workflows/_deploy.yml
    needs: [vars, build]
    with:
      environment: stage
      chart_name: admin-portal
      chart_version: '0.1.0'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.sha_short }}