name: Build and deploy admin-portal
on:
  push:
    branches:
      - SIK-2015

jobs:
  # vars:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     stage_bucket_name: ${{ steps.vars.outputs.stage_bucket_name }}
  #     stage_subdomain: ${{ steps.vars.outputs.stage_subdomain }}
  #     https_domain: ${{ steps.vars.outputs.https_domain }}
  #     prod_bucket_name: ${{ steps.vars.outputs.prod_bucket_name }}
  #     prod_subdomain: ${{ steps.vars.outputs.prod_subdomain }}
  #   steps:
  #     - id: vars
  #       run: |
  #         echo "stage_bucket_name=gundi-portal-default-2967630079" >> $GITHUB_OUTPUT
  #         echo "stage_subdomain=stage" >> $GITHUB_OUTPUT
  #         echo "https_domain=gundiservice.org" >> $GITHUB_OUTPUT
  #         echo "prod_bucket_name=gundi-portal-default-75032777" >> $GITHUB_OUTPUT
  #         echo "prod_subdomain=admin" >> $GITHUB_OUTPUT

  build:
    uses: ./.github/workflows/_build.yml
    # needs: vars
    with:
      environment: stage

  # deploy_stage:
  #   uses: ./.github/workflows/_deploy.yml
  #   needs: [vars, build]
    # with:
    #   environment: stage
  #     bucket_name: ${{ needs.vars.outputs.stage_bucket_name }}
  #     subdomain: ${{ needs.vars.outputs.stage_subdomain }}
  #     https_domain: ${{ needs.vars.outputs.https_domain }}

  # deploy_prod:
  #   uses: ./.github/workflows/_deploy.yml
  #   needs: [vars, deploy_stage]
  #   with:
  #     environment: prod
  #     bucket_name: ${{ needs.vars.outputs.prod_bucket_name }}
  #     subdomain: ${{ needs.vars.outputs.prod_subdomain }}
  #     https_domain: ${{ needs.vars.outputs.https_domain }}
