name: Build and deploy admin-portal
on:
  push:
    branches:
      - main
      - gundi-3054 # remove this line before merge
      - 'release-**'

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      repository: ${{ steps.vars.outputs.repository }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          echo "tag=${{ github.head_ref || github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repository=us-central1-docker.pkg.dev/cdip-78ca/gundi/admin-portal" >> $GITHUB_OUTPUT

  build:
    uses: PADAS/gundi-workflows/.github/workflows/build_docker.yml@v2
    needs: vars
    with:
      environment: stage
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}

  unit-test:
    uses: .github/workflows/_unit-tests.yml
    needs: build
    with:
      image: "us-central1-docker.pkg.dev/cdip-78ca/gundi/admin-portal:${{ github.head_ref || github.ref_name }}-${{ github.run_number }}"
      # image: "europe-west3-docker.pkg.dev/padas-app/er-mt/das-server:${{ github.head_ref || github.ref_name }}-${{ github.run_number }}"
      command: |
        pytest 

  deploy_dev:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v2
    if: startsWith(github.ref, 'refs/heads/main')
    needs: [vars, build]
    with:
      environment: dev
      chart_name: admin-portal
      chart_version: '1.0.2'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
    secrets: inherit

  deploy_stage:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v2
    if: startsWith(github.ref, 'refs/heads/release')
    needs: [vars, build]
    with:
      environment: stage
      chart_name: admin-portal
      chart_version: '1.0.2'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
    secrets: inherit

  deploy_prod:
    uses: PADAS/gundi-workflows/.github/workflows/deploy_k8s.yml@v2
    if: startsWith(github.ref, 'refs/heads/release')
    needs: [vars, build, deploy_stage]
    with:
      environment: prod
      chart_name: admin-portal
      chart_version: '1.0.2'
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
    secrets: inherit
