# Generated by Django 3.1 on 2021-02-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_auto_20201012_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Owner"),
        ),
    ]
